services:
  postgres:
    container_name: matrixss
    image: "postgres:14.4"
    environment:
      POSTGRES_USER: matrixss
      POSTGRES_PASSWORD: matrixss
      POSTGRES_DB: matrixssdb
      POSTGRES_HOST: matrixss
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"
    expose:
      - "5432"
  postgresadmin:
    image: dpage/pgadmin4
    container_name: postgresadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8888:80"
    depends_on:
      - postgres
